Generate a software bill of materials SBOM as part of the build process (#459)
* Adds SBOM to pipeline

diff --git a/.github/workflows/release.yml b/.github/workflows/release.yml
--- a/.github/workflows/release.yml
+++ b/.github/workflows/release.yml
@@ -1,17 +1,49 @@
 name: Release Workbench
 
 on:
-  release:
-    types: [published]
+  push:
+    tags:
+      - 'v*'
 
 defaults:
   run:
     shell: bash
 
 jobs:
+  release:
+    name: Create Release
+    runs-on: ubuntu-latest
+    steps:
+      - name: Checkout code
+        uses: actions/checkout@v2
+
+      - name: Fail if tag is not prefixed by v
+        run: |
+          if [[ $GITHUB_REF_NAME =~ ^v[0-9]+\.[0-9]+\.[0-9].* ]]; then
+              echo "Valid version format"
+          else
+              echo "Invalid version format"
+              exit 1
+          fi
+
+      - name: Create release
+        env:
+          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
+          tag: ${{ github.ref_name }}
+        run: |
+          OPTIONS=""
+          if [[ $GITHUB_REF_NAME == *"internal"* ]] || [[ $GITHUB_REF_NAME == *"beta"* ]]; then
+            OPTIONS="--draft"
+          fi
+          gh release create "$GITHUB_REF_NAME" \
+              --repo="$GITHUB_REPOSITORY" \
+              --title="Release for ${GITHUB_REF_NAME}" \
+              --generate-notes $OPTIONS
+
   build:
     name: Build on ${{ matrix.target }}
     runs-on: ${{ matrix.os }}
+    needs: [release]
     strategy:
       matrix:
         include:
@@ -165,8 +197,8 @@ jobs:
       - name: Build signed installer
         if: runner.os == 'Windows'
         run: |
-          azuresigntool.exe sign --verbose -kvu ${{ secrets.AZURE_KEY_VAULT_URI }} -kvc ${{ secrets.AZURE_KEYVAULT_CERT_NAME }} -kva %AZ_TOKEN% -fd sha256 -tr http://timestamp.digicert.com -v "dist/AxonOps Workbench-%VERSION%-win-x64.exe"
-          azuresigntool.exe sign --verbose -kvu ${{ secrets.AZURE_KEY_VAULT_URI }} -kvc ${{ secrets.AZURE_KEYVAULT_CERT_NAME }} -kva %AZ_TOKEN% -fd sha256 -tr http://timestamp.digicert.com -v "dist/AxonOps Workbench-%VERSION%-win-x64.msi"
+          azuresigntool.exe sign --verbose -kvu ${{ secrets.AZURE_KEY_VAULT_URI }} -kvc ${{ secrets.AZURE_KEYVAULT_CERT_NAME }} -kva %AZ_TOKEN% -fd sha256 -tr http://timestamp.digicert.com -v "dist/AxonOps.Workbench-%VERSION%-win-x64.exe"
+          azuresigntool.exe sign --verbose -kvu ${{ secrets.AZURE_KEY_VAULT_URI }} -kvc ${{ secrets.AZURE_KEYVAULT_CERT_NAME }} -kva %AZ_TOKEN% -fd sha256 -tr http://timestamp.digicert.com -v "dist/AxonOps.Workbench-%VERSION%-win-x64.msi"
         shell: cmd
 
       # Ensure this task is right before the Upload
@@ -202,10 +234,17 @@ jobs:
         env:
           GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
 
+      - name: Create SBOM xml
+        uses: CycloneDX/gh-node-module-generatebom@v1
+        with:
+          path: './'
+          output: 'dist/workbench.bom.xml'
+
       - name: Upload Artifacts
         uses: softprops/action-gh-release@v2
         with:
           files: |
+            dist/workbench.bom.xml
             dist/*.zip
             dist/*.pkg
             dist/*.dmg
@@ -219,8 +258,22 @@ jobs:
         env:
           GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
 
-# Release choco and brew
+  generate-sbom:
+    runs-on: ubuntu-latest
+    needs: [build]
+    if: ${{ !cancelled() && success() }}
+    steps:
+      - name: Generate SBOM
+        uses: anchore/sbom-action@v0
+        with:
+          artifact-name: sbom.spdx
 
+      - name: Publish SBOM
+        uses: anchore/sbom-action/publish-sbom@v0
+        with:
+          sbom-artifact-match: ".*\\.spdx$"
+
+# Release choco and brew
   release-brew:
     runs-on: ubuntu-latest
     needs: [build]
@@ -238,8 +291,10 @@ jobs:
 
       - name: Make changes to Homebrew
         run: |
-          VERSION=$(echo $GITHUB_REF_NAME | sed 's/^v//g')
-          echo "VERSION=$VERSION" >> $GITHUB_ENV
+          set -x
+          if [[ "$VERSION" == "" ]]; then
+            VERSION=$(echo $GITHUB_REF_NAME | sed 's/^v//g')
+          fi
           case $VERSION in
             *internal*)
               NAME=axonopsworkbench-internal
@@ -258,8 +313,8 @@ jobs:
           git config user.name "GitHub Actions"
           git config user.email "actions@github.com"
           # Get the sha256sum
-          SHA_ARM=$(curl -sfL ${GITHUB_URL}/${VERSION}/AxonOps.Workbench-${VERSION}-mac-arm64.zip.sha256sum | awk '{print $1}')
-          SHA_AMD=$(curl -sfL ${GITHUB_URL}/${VERSION}/AxonOps.Workbench-${VERSION}-mac-x64.zip.sha256sum | awk '{print $1}')
+          SHA_ARM=$(curl -sfL ${GITHUB_URL}/v${VERSION}/AxonOps.Workbench-${VERSION}-mac-arm64.zip.sha256sum | awk '{print $1}')
+          SHA_AMD=$(curl -sfL ${GITHUB_URL}/v${VERSION}/AxonOps.Workbench-${VERSION}-mac-x64.zip.sha256sum | awk '{print $1}')
           # Update versions
           cp $TEMPLATE $CONFIG_FILE
           sed -i "s/%SHA_ARM%/$SHA_ARM/g" $CONFIG_FILE
@@ -304,13 +359,15 @@ jobs:
 
       - name: Make changes to chocolatey
         run: |
-          VERSION=$(echo $GITHUB_REF_NAME | sed 's/^v//g')
-          echo "VERSION=$VERSION" >> $GITHUB_ENV
+          if [[ "$VERSION" == "" ]]; then
+            VERSION=$(echo $GITHUB_REF_NAME | sed 's/^v//g')
+          fi
+          #echo "VERSION=$VERSION" >> $GITHUB_ENV
           cd chocolatey
           git config user.name "GitHub Actions"
           git config user.email "actions@github.com"
           # Get the sha256sum
-          SHA_AMD=$(curl -sfL ${GITHUB_URL}/${VERSION}/AxonOps.Workbench-${VERSION}-win-x64.exe.sha256sum | awk '{print $1}')
+          SHA_AMD=$(curl -sfL ${GITHUB_URL}/v${VERSION}/AxonOps.Workbench-${VERSION}-win-x64.msi.sha256sum | awk '{print $1}')
           # Update versions
           cp $TEMPLATE $CONFIG_FILE
           sed -i "s/%SHA_AMD%/$SHA_AMD/g" $CONFIG_FILE
@@ -354,9 +411,13 @@ jobs:
 
       - name: "Set runtime variables"
         run: |
+          if [[ "$VERSION" == "" ]]; then
+            VERSION=$(echo $GITHUB_REF_NAME | sed 's/^v//g')
+          fi
           PUBLISH="yes"
           DEBIAN_ARCHS="amd64"
           REDHAT_ARCHS="x86_64"
+          VERSION=$(echo $GITHUB_REF_NAME | sed 's/^v//g')
           case $VERSION in
             *internal*)
               PUBLISH="no"
@@ -376,8 +437,11 @@ jobs:
       - name: Push Debian package
         if: env.PUBLISH == 'yes'
         run: |
+          if [[ "$VERSION" == "" ]]; then
+            VERSION=$(echo $GITHUB_REF_NAME | sed 's/^v//g')
+          fi
           for arch in ${{ env.DEBIAN_ARCHS }}; do
-            curl -sLO "https://github.com/axonops/axonops-workbench-cassandra/releases/download/$VERSION/AxonOps.Workbench-$VERSION-linux-${arch}.deb"
+            curl -sLO "https://github.com/axonops/axonops-workbench-cassandra/releases/download/v$VERSION/AxonOps.Workbench-$VERSION-linux-${arch}.deb"
             gcloud config set project axonops-public
             gcloud artifacts apt upload axonops-apt-${env.REPO_SUFFIX} --location=europe --source=AxonOps.Workbench-$VERSION-linux-${arch}.deb
           done
@@ -385,8 +449,11 @@ jobs:
       - name: Push RedHat package
         if: env.PUBLISH == 'yes'
         run: |
+          if [[ "$VERSION" == "" ]]; then
+            VERSION=$(echo $GITHUB_REF_NAME | sed 's/^v//g')
+          fi
           for arch in ${{ env.REDHAT_ARCHS }}; do
-            curl -sLO "https://github.com/axonops/axonops-workbench-cassandra/releases/download/$VERSION/AxonOps.Workbench-$VERSION-linux-${arch}.rpm"
+            curl -sLO "https://github.com/axonops/axonops-workbench-cassandra/releases/download/v$VERSION/AxonOps.Workbench-$VERSION-linux-${arch}.rpm"
             gcloud config set project axonops-public
             gcloud artifacts yum upload axonops-yum-${env.REPO_SUFFIX} --location=europe --source=AxonOps.Workbench-$VERSION-linux-${arch}.rpm
           done
